### ISSUE TITLE
mjsunit/regress/regress-500980 on 8911 board

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#153]
Fails like this on popcorn board:

```
# Fatal error in CALL_AND_RETRY_LAST
# Allocation failed - process out of memory
```

The popcorn boards have only 384MB, however, they do have 2GB swap setup (at least on the board I checked. This test does not fail on error-8 board, with 2GB ram.

**Comment by kilvadyb** [comment]
On our popcorn board (with 1 GB swap) we got:

```
$ out/mipsel.release/d8 --test --random-seed=-249539155 --nocrankshaft --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/regress/regress-500980.js

<--- Last few GCs --->

     113 ms: Mark-sweep 0.8 (18.5) -> 0.8 (18.5) MB, 16.0 / 0 ms [allocation failure] [GC in old space requested].
...
#
# Fatal error in CALL_AND_RETRY_LAST
# Allocation failed - process out of memory
#

Aborted
```

The script is quite simple:

```
var a = "a";
assertThrows(function() { while (true) a += a; }, RangeError);
assertThrows(function() { a in a; }, TypeError);
```

The test passes if I comment out any of the assert lines. I tried to investigate the value for RangeError.
RangeError is thrown from

```
#0  v8::internal::Factory::NewRangeError(v8::internal::MessageTemplate::Template, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) () at ../src/factory.cc:1122
#1  0x00d31710 in v8::internal::Factory::NewInvalidStringLengthError() () at .././src/factory.h:542
#2  0x00d3f014 in v8::internal::Factory::NewConsString(v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>) () at ../src/factory.cc:477
#3  0x0146bda8 in v8::internal::__RT_impl_Runtime_StringAddRT(v8::internal::Arguments, v8::internal::Isolate*) ()
    at ../src/runtime/runtime-strings.cc:325
#4  0x0146bbf0 in v8::internal::Runtime_StringAddRT(int, v8::internal::Object**, v8::internal::Isolate*) ()
    at ../src/runtime/runtime-strings.cc:318
```

And the limit value is: 

```
  // Maximal string length.
  static const int kMaxLength = (1 << 28) - 16;
```

So I think the string 'a' contains (1 << 28) - 16 characters after the RangeError and 'a in a;' tries to load 'a' two times into memory which requires 0x1FFFFFE0 memory (it is under 1 GB). So I will check what happens in the code of 'a in a'.

**Comment by paul99** [comment]
This seems to have been fixed by Yang Guo CL https://codereview.chromium.org/1214373005

Balázs, can you verify this, and close this issue if it is truly fixed?

**Comment by kilvadyb** [comment]
Tests are passed in debug and release mode as well building from the above CL or ToT.
