### ISSUE TITLE
mjsunit/d8-os fails on MIPS64R6 qemu-system and MIPS64R6 board

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#199]
mjsunit/d8-os fails on MIPS64R6 qemu-system and MIPS64R6 board with following message. The test doesn't fail on qemu-user

```
[root@mips32r6-le-hf o_main]#  /home/ivica/src/o_main/v8/out/mips64el.optdebug/d8 --test --random-seed=1487570042 --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap /home/ivica/src/o_main/v8/test/mjsunit/mjsunit.js /home/ivica/src/o_main/v8/test/mjsunit/d8-os.js
Warning: unknown flag --enable-slow-asserts.
Try --help for options
ls: cannot access /tmp/d8-os-test-directory-185479022: No such file or directory
ls: cannot access /tmp/d8-os-test-directory-185479022/dir/bar: No such file or directory
/home/ivica/src/o_main/v8/test/mjsunit/mjsunit.js:334: Did not throw exception

Stack: Error
    at new MjsUnitAssertionError (/home/ivica/src/o_main/v8/test/mjsunit/mjsunit.js:31:16)
    at assertThrows (/home/ivica/src/o_main/v8/test/mjsunit/mjsunit.js:334:11)
    at /home/ivica/src/o_main/v8/test/mjsunit/d8-os.js:96:5
    throw new MjsUnitAssertionError("Did not throw exception");
    ^
Error
    at new MjsUnitAssertionError (/home/ivica/src/o_main/v8/test/mjsunit/mjsunit.js:31:16)
    at assertThrows (/home/ivica/src/o_main/v8/test/mjsunit/mjsunit.js:334:11)
    at /home/ivica/src/o_main/v8/test/mjsunit/d8-os.js:96:5
```

**Comment by dusmil** [comment]
Not real failure. You ran the test as root user.

**Comment by ibogosavljevic** [comment]
LGTM :smiley: 

The test says explicitly `// This test fails if you are root since root can read any dir.`
