### ISSUE TITLE
install-sysroot.py breaking builds in gclient runhooks step

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#332]
After commit c4fab3ec2566, the gclient runhooks step now runs a script called install-sysroot.py.  This script is unaware of little endian MIPS or MIPS64.  Note that the Edge Router Pro boards report their architecture as "mips64".    Here is the error message we see when the script is run on an Edge Router Pro board:

```
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/bbv8-slaves/cavoct3-board-1/build/slave/v8-linux-mipsel-target-edge-webkit/build'
Unrecognized host arch: mips64
Error: Command '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' returned non-zero exit status 1 in /bbv8-slaves/cavoct3-board-1/build/slave/v8-linux-mipsel-target-edge-webkit/build
step returned non-zero exit code: 2 
```

Here is the error we see when the script is run on a build machine (x86):

```
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/bbv8-slaves/mips-sim-11/build/slave/v8-linux-mips-debug-target-edge-no-i18n-builder/build'
Installing Debian Wheezy amd64 root image: /bbv8-slaves/mips-sim-11/build/slave/v8-linux-mips-debug-target-edge-no-i18n-builder/build/v8/build/linux/debian_wheezy_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c52471d9dec240c8d0a88fa98aa1eefeee32e22f/debian_wheezy_amd64_sysroot.tgz
Traceback (most recent call last):
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 219, in <module>
    sys.exit(main(sys.argv[1:]))
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 148, in main
    InstallDefaultSysroots()
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 122, in InstallDefaultSysroots
    InstallSysroot(host_arch)
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 205, in InstallSysroot
    ['curl', '--fail', '--retry', '3', '-L', url, '-o', tarball])
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' returned non-zero exit status 1 in /bbv8-slaves/mips-sim-11/build/slave/v8-linux-mips-debug-target-edge-no-i18n-builder/build
step returned non-zero exit code: 2
```

**Comment by MIPSbkirby** [comment]
It looks like part of the problem is that curl needs to be installed on the all the slave machines.  That's been done.  Also, the following patch needs to be applied to detect_host_arch.py so that it will return "mips" as the architecture on any board that returns "mips64" for the architecture. 

```
diff -ru a/build/detect_host_arch.py b/build/detect_host_arch.py
--- a/build/detect_host_arch.py 2016-06-08 18:40:26.222103996 -0700
+++ b/build/detect_host_arch.py 2016-06-08 17:04:15.862304833 -0700
@@ -21,6 +21,8 @@
     host_arch = 'x64'
   elif host_arch.startswith('arm'):
     host_arch = 'arm'
+  elif host_arch.startswith('mips'):
+    host_arch = 'mips'

   # platform.machine is based on running kernel. It's possible to use 64-bit
   # kernel with 32-bit userland, e.g. to give linker slightly more memory.
```

The patch is applied in the "Apply patch" step, but it needs to be committed upstream (assuming this is the only problem...)

**Comment by MIPSbkirby** [comment]
It looks like the detect_host_arch.py module is in the https://chromium.googlesource.com/chromium/src/build repository.  The above patch needs to get committed there so that we can remove our local patch.

**Comment by MIPSbkirby** [comment]
The patch has been applied to the Chromium tree and that version has been merged into V8.  So, the gclient runhooks step is working in the upstream builders again and our local patch has been removed.  These sysroots don't seem to be effecting our builds either.
