### ISSUE TITLE
Bughunting: webkit and mozilla test failures

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#346]
### The following tests are failing:

It seems they are introduced by https://codereview.chromium.org/2107163002

mozilla/js1_5/Regress/regress-191633
mozilla/js1_5/Regress/regress-366601
mozilla/js1_5/Regress/regress-367561-01
mozilla/js1_5/Expressions/regress-394673 (flaky in a repeated run)

```
#
# Fatal error in CALL_AND_RETRY_LAST
# Allocation failed - JavaScript heap out of memory
#
```

---

mozilla/ecma_3/RegExp/regress-209067

```
/bbv8-slaves/mips-sim-12/build/slave/v8-linux-mipsel-sim-edge-mozilla/build/v8/test/mozilla/data/ecma_3/RegExp/regress-209067.js:81: TypeError: Cannot read property '3' of null
                p=p.replace(/\\'/g,'\\&#39;').replace(/\\"/g,'\\&#34;').replace(/^\s/,'');
                                                                        ^
TypeError: Cannot read property '3' of null
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /bbv8-slaves/mips-sim-12/build/slave/v8-linux-mipsel-sim-edge-mozilla/build/v8/test/mozilla/data/ecma_3/RegExp/regress-209067.js:81:73
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at formatHTML (/bbv8-slaves/mips-sim-12/build/slave/v8-linux-mipsel-sim-edge-mozilla/build/v8/test/mozilla/data/ecma_3/RegExp/regress-209067.js:75:7)
    at /bbv8-slaves/mips-sim-12/build/slave/v8-linux-mipsel-sim-edge-mozilla/build/v8/test/mozilla/data/ecma_3/RegExp/regress-209067.js:130:1
```

---

mozilla/js1_5/extensions/regress-446386

```
============ Stress 1/5 ============
BUGNUMBER: 446386
STATUS: Do not crash throwing error without compiler pseudo-frame
Test skipped. evalcx required.
 PASSED! Do not crash throwing error without compiler pseudo-frame
============ Stress 2/5 ============
BUGNUMBER: 446386
STATUS: Do not crash throwing error without compiler pseudo-frame
Test skipped. evalcx required.
 PASSED! Do not crash throwing error without compiler pseudo-frame
============ Stress 3/5 ============
BUGNUMBER: 446386
STATUS: Do not crash throwing error without compiler pseudo-frame
Test skipped. evalcx required.
 PASSED! Do not crash throwing error without compiler pseudo-frame
============ Stress 4/5 ============
BUGNUMBER: 446386
STATUS: Do not crash throwing error without compiler pseudo-frame
Test skipped. evalcx required.
 PASSED! Do not crash throwing error without compiler pseudo-frame
============ Stress 5/5 ============
BUGNUMBER: 446386
STATUS: Do not crash throwing error without compiler pseudo-frame
 FAILED! [reported from test()] Do not crash throwing error without compiler pseudo-frame : Expected value '', Actual value 'TypeError: evalcx is not a function' 
======== Full Deoptimization =======
```

webkit/dfg-check-two-structures

```
PASS foo(o, o) is 42
FAIL foo(o, o) should be 46. Was 75.
PASS foo(o, o) is 46
```

**Comment by palfia** [comment]
Fixed by #351
