### ISSUE TITLE
Add softfloat jobs for the 3.17 branch

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#43]

**Comment by palfia** [comment]
Today, I managed to finish our softfloat rootfs (uclibc based for now, eglibc based is in progress) for the malta board, so I quickly executed the cctest and mjsunit suites on the board:

The release cctests has finished without any failure.

However, the release mjsunit has finished with a few test failure:
- regress-2294 - 3x
- the "usual" regress-crbug-160010 with OOM - 3x
- compiler/uint32 - 3x

Details:
=== release uint32 ===  
Path: mjsunit/compiler/uint32
/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:166: Failure: expected <4294967295> found <4.538803003564299e-307>
    throw new MjsUnitAssertionError(message);
          ^
Error
    at new MjsUnitAssertionError (/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:31:16)
    at fail (/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:166:11)
    at assertEquals (/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:237:7)
    at /data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/compiler/uint32.js:49:3
Command: /data/palfia/v8/v8_git_svn/v8.git/out/mipsel.release/d8 --nobreak-on-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax --expose-gc /data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js /data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/compiler/uint32.js --test

=== release regress-2294 ===  
Path: mjsunit/regress/regress-2294
============ Stress 1/5 ============
/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:166: Failure: expected <0> found <2>
    throw new MjsUnitAssertionError(message);
          ^
Error
    at new MjsUnitAssertionError (/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:31:16)
    at fail (/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:166:11)
    at assertEquals (/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js:237:7)
    at test (/data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/regress/regress-2294.js:36:3)
    at /data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/regress/regress-2294.js:67:1
Command: /data/palfia/v8/v8_git_svn/v8.git/out/mipsel.release/d8 --stress-opt --always-opt --nobreak-on-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax /data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/mjsunit.js /data/palfia/v8/v8_git_svn/v8.git/test/mjsunit/regress/regress-2294.js --test

Environment:
- Linux 3.7.8 for malta
- rootfs created with buildroot (toolchain: buildroot uclibc and gcc 4.6)

V8 was compiled with the buildroot toolchain in softfloat mode (I had to cherry pick r14172 to the 3.17 branch to be able to compile V8 with uclibc).

**Comment by palfia** [comment]
New test results with eglibc based rootfs:
- mjsunit/regress/regress-2294: runs correctly
- mjsunit/compiler/uint32: unfortunately, this error is still exist, but the output is slighty different:
  
  # out/mipsel.release/d8 --nobreak-on-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax --expose-gc test/mjsunit/mjsunit.js test/mjsunit/compiler/uint32.js --test
  test/mjsunit/mjsunit.js:166: Failure: expected <4294967295> found <4.628153625694979e-306>
      throw new MjsUnitAssertionError(message);
            ^
  Error
      at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
      at fail (test/mjsunit/mjsunit.js:166:11)
      at assertEquals (test/mjsunit/mjsunit.js:237:7)
      at test/mjsunit/compiler/uint32.js:49:3
