### ISSUE TITLE
Bughunting: mjsunit/compiler/regress-694088 fails

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#465]
Test mjsunit/compiler/regress-694088 fails on following builders: 

https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1817/steps/Check/logs/regress-694088
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/8715/steps/Check/logs/regress-694088
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge/builds/11807/steps/Check/logs/regress-694088

**Comment by ilijapavlovic** [comment]
The problem appears after:

Commit: 3c36aacc87f701fea0bb6976a4498dde61929a29
Subject:  [turbofan] Fix handling of typed array loads in load elimination.
Review-Url: https://codereview.chromium.org/2725593002

The test `mjsunit/compiler/regress-694088` is introduced with this commit.

**Comment by ilijapavlovic** [comment]
The error is locally reproduced:
```
+ out/Release/d8 --test --random-seed=-1 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/compiler/regress-694088.js
test/mjsunit/mjsunit.js:257: Failure: expected <0> found <1072693248>

Stack: Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:257:11)
    at assertEquals (test/mjsunit/mjsunit.js:328:7)
    at test/mjsunit/compiler/regress-694088.js:15:3
    at test/mjsunit/compiler/regress-694088.js:16:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:257:11)
    at assertEquals (test/mjsunit/mjsunit.js:328:7)
    at test/mjsunit/compiler/regress-694088.js:15:3
    at test/mjsunit/compiler/regress-694088.js:16:3
```

**Comment by ilijapavlovic** [comment]
The problem was that the test was prepared only for little endian platforms - not for big endian.
In the test is added check for little or big endian platforms. Accordingly the test will return adequate value.

CL is uploaded: https://codereview.chromium.org/2739403002/

**Comment by ilijapavlovic** [comment]
CL committed and landed:
https://chromium.googlesource.com/v8/v8/+/d9bcc067caa93d4cebeb0efe0a9370a7b931e664

On buildbots the test is successful:
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1830
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/8749
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge/builds/11845
