### ISSUE TITLE
Bughunting: mjsunit/asm/poppler/poppler

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#513]
Test `mjsunit/asm/poppler/poppler` fails on following test environments:
    https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/11469
    https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/11436
    https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge%20-%20mipsr6/builds/6744
    https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mipsr6/builds/6537
    https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/9472
    https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/2121
    https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/2192
    https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/2726
    https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/679
    https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/636
    https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang/builds/946

**Comment by ilijapavlovic** [comment]
The problem starts with CL
   `57031e82db6864b0c0caa67502b222a255ef9a96 [asm.js] Enable --validate-asm by default.`
   https://chromium-review.googlesource.com/c/583655

**Comment by ilijapavlovic** [comment]
Mentioned CL enables validating asm.js modules before compiling in `src/flag-definitions.h`.

**Comment by ilijapavlovic** [comment]
In `v8/src/mips64/assembler-mips64.cc` is defined following function:
```
void Assembler::GenInstrImmediate(Opcode opcode, Register rs, Register rt, int32_t j,
                                  CompactBranchType is_compact_branch) {
  DCHECK(rs.is_valid() && rt.is_valid() && (is_int16(j) || is_uint16(j)));
  Instr instr = opcode | (rs.code() << kRsShift) | (rt.code() << kRtShift)
      | (j & kImm16Mask);
  emit(instr, is_compact_branch);
}
```
For mips64el r2 in debug mode, argument `j` has value `0x471dc` which is not 16-bit, and this value causes unsuccessful test execution.

**Comment by ilijapavlovic** [comment]
In `v8/src/compiler/code-generator.cc` function `CodeGenerator::AssembleBlock(const InstructionBlock* block)` emits following instruction:
```
          [a6|R|w32] = CheckedLoadWord32 : MRI #291292 [a5|R|w64] [a0|R|w64]
```
Hexadecimal representation of `291292` is `0x471DC` and this value is used as offset.
For this instruction is assembled architecture-specific code/instruction. In this case it is following:
```
// v8/src/compiler/mips64/code-generator-mips64.cc

CodeGenerator::CodeGenResult CodeGenerator::AssembleArchInstruction(Instruction* instr) {
...
    case kCheckedLoadWord32:
      ASSEMBLE_CHECKED_LOAD_INTEGER(lw);     // Line 1829
      break;
...
```

This is content of the call stack in the moment when failure happens:
```
#0  v8::internal::Assembler::GenInstrImmediate (this=0x121355b70, opcode=<optimized out>, rs=..., rt=..., j=<optimized out>, is_compact_branch=v8::internal::Assembler::CompactBranchType::NO)
 at ../../src/mips64/assembler-mips64.cc:1130
#1  0x00000001207f68b0 in v8::internal::Assembler::lw (this=<optimized out>, rd=..., rs=...)
 at ../../src/mips64/assembler-mips64.cc:2275
#2  0x0000000120853384 in v8::internal::compiler::CodeGenerator::AssembleArchInstruction (this=<optimized out>, instr=<optimized out>)
 at ../../src/compiler/mips64/code-generator-mips64.cc:1829
...
```

Function `Assembler::GenInstrImmediate(...)` checks that passed offset is 16-bit value, and for this case the offset has invalid value.

This error can be fixed if macro-assembler version of LW instruction is emitted instead normal LW instruction. The same approach can be applied to SW instruction, and all other instructions for load and store data.
```
...
    case kCheckedLoadWord32:
      ASSEMBLE_CHECKED_LOAD_INTEGER(Lw);     // Macro-assembler instruction.
      break;
...
    case kAtomicStoreWord32:
      ASSEMBLE_ATOMIC_STORE_INTEGER(Sw);     // Macro-assembler instruction.
      break;

```

**Comment by ilijapavlovic** [comment]
CL is uploaded: https://chromium-review.googlesource.com/c/608975
This CL should fix following tests:
- mjsunit/asm/poppler/poppler
- mjsunit/asm/sqlite3/sqlite
- mjsunit/asm/sqlite3/sqlite-pointer-masking

**Comment by ilijapavlovic** [comment]
CL landed: https://chromium.googlesource.com/v8/v8/+/ef3ad19b63a701df6139f6753e6d5b2e893a7e64

**Comment by ilijapavlovic** [comment]
The test still fails with Clang:
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang/builds/952/steps/Check/logs/stdio/text

**Comment by ilijapavlovic** [comment]
CL is tested locally with Clang build and the tests were successful.
In last several days, mentioned buildbot did not run, so the latest CLs are not tested on this buildbot.

**Comment by ilijapavlovic** [comment]
The tests are successful again.
