### ISSUE TITLE
Using GN to configure V8 using fpxx using the mips_fpu_mode=fpxx flag generates errors

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#546]
Setting the `mips_fpu_mode=fpxx` flag in GN to compile with the fpxx flags just generates the error message "Undefined identifier":

```
$ buildtools/linux64/gn gen //out/Release --args='is_clang=false is_debug=false mips_arch_variant="r2" target_cpu="mipsel" treat_warnings_as_errors=false use_sysroot=false mips_fpu_mode=fpxx' --check
ERROR at the command-line "--args":1:137: Undefined identifier
is_clang=false is_debug=false mips_arch_variant="r2" target_cpu="mipsel" treat_warnings_as_errors=false use_sysroot=false mips_fpu_mode=fpxx
                                                                                                                                                              ^---
```

Technically the builder will use a command like the following to generate the build files:
```
$ python -u tools/mb/mb.py gen -m client.v8-mips -b 'Target - edge - fpxx - builder' --config-file ./mb_mips_config.pyl '--gyp-script=gypfiles/gyp_v8' //out/Release
Traceback (most recent call last):
  File "tools/mb/mb.py", line 67, in Main
    ret = self.args.func()
  File "tools/mb/mb.py", line 317, in CmdGen
    return self.RunGNGen(vals)
  File "tools/mb/mb.py", line 824, in RunGNGen
    gn_args = self.GNArgs(vals)
  File "tools/mb/mb.py", line 1019, in GNArgs
    gn_args = gn_helpers.ToGNString(gn_helpers.FromGNArgs(gn_args))
  File "/export/tmp/bkirby/v8-gn-testing/testbb/build/scripts/slave/.recipe_deps/recipe_engine/workdir/v8/build/gn_helpers.py", line 124, in FromGNArgs
    return parser.ParseArgs()
  File "/export/tmp/bkirby/v8-gn-testing/testbb/build/scripts/slave/.recipe_deps/recipe_engine/workdir/v8/build/gn_helpers.py", line 213, in ParseArgs
    val = self._ParseAllowTrailing()
  File "/export/tmp/bkirby/v8-gn-testing/testbb/build/scripts/slave/.recipe_deps/recipe_engine/workdir/v8/build/gn_helpers.py", line 237, in _ParseAllowTrailing
    raise GNException("Unexpected token: " + self.input[self.cur:])
GNException: Unexpected token: fpxx

```

To run this on your desk, copy the following file into the current directory and name it `mb_mips_config.pyl`:
[mb_mips_config.pyl.txt](https://github.com/v8mips/v8mips/files/1519774/mb_mips_config.pyl.txt)

**Comment by ibogosavljevic** [comment]
The problem is that fpxx is not surrounded by quotes, the same way as in target_cpu="mipsel", where mipsel is surrounded by quotes

**Comment by MIPSbkirby** [comment]
Not having `fpxx` in quotes fixed the problem.   It looks like it compiled with the fpxx flags and the binary runs on a board.  So, this is fixed.
