### ISSUE TITLE
Failures on OCTANE 2.0 benchmark

### ISSUE THREAD

**Issue by dusmil** [v8mips/v8mips#67]
Currently v8 for mips fails on new octane benchmark on HW and simulator.
The failures do not exist on ARM .

Tested revision r18097.

Error log:

```
../out/mipsel.release/d8 run.js
Richards: 816
DeltaBlue: 431
Crypto: 584
RayTrace: 557
EarleyBoyer: 759
RegExp: 90.3
Splay: 528
SplayLatency: 1602
NavierStokes: 373
PdfJS: 198
Mandreel: 224
MandreelLatency: NaN
Gameboy: 697
CodeLoad: 525
Box2D: 216
zlib: Assertion failed: , at: ,25, at Error
    at Error (native)
    at $.___assert_func (eval at InitializeZlibBenchmark (zlib-data.js:65:37), <anonymous>:1:182843)
    at a1 (eval at InitializeZlibBenchmark (zlib-data.js:65:37), <anonymous>:1:116423)
    at Object.a2 [as _main] (eval at InitializeZlibBenchmark (zlib-data.js:65:37), <anonymous>:1:117075)
    at Object.Module.callMain (eval at InitializeZlibBenchmark (zlib-data.js:65:37), <anonymous>:1:184106)
    at b (eval at InitializeZlibBenchmark (zlib-data.js:65:37), <anonymous>:1:184340)
    at Ya (eval at InitializeZlibBenchmark (zlib-data.js:65:37), <anonymous>:1:184948)
    at Benchmark.runZlib [as run] (zlib.js:39:3)
    at Measure (base.js:274:17)
    at BenchmarkSuite.RunSingleBenchmark (base.js:292:5)
Typescript: 405

```

**Comment by paul99** [comment]
Thanks for testing, Dusan. For everyone, this is top priority after daily porting. Hopefully this will be easier than the last one :-)

**Comment by dusmil** [comment]
Fix submitted:
https://codereview.chromium.org/95203005/

**Comment by paul99** [comment]
The fix was landed in r 18168. Closing.
